# file: cassandra/tasks/package_configure.yml
- name: Stop cassandra because it is autostarted after install
  service:
    name: cassandra
    state: stopped

- name: Clear logs to remove autostart cruft 
  shell: echo  > /var/log/cassandra/system.log

- name: acquire cluster_name from cassandra.yaml to determine if this is a fresh install
  shell: cat /etc/cassandra/cassandra.yaml  | grep "cluster_name"
  register: fresh_install

- name: Clear system data dir after autostart only if fresh install (cluster_name == "Test Cluster")
  shell: rm -rf /var/lib/cassandra/data/system/*
  when: fresh_install.stdout.find('Test Cluster') >= 0

- name: Cassandra | Update the cassandra configuration
  template:
    src: "{{item}}.j2"
    dest: "/etc/cassandra/{{item}}"
    owner: "{{cassandra_user}}"
    group: "{{cassandra_group}}"
    mode: 0644
  with_items:
    - "cassandra-env.sh"
    - "cassandra.yaml"

- name: Restart cassandra
  service:
    name: cassandra
    state: restarted
